// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Additional model parameters for chat completion.
public type ChatOptions record {
    # Number of tokens to keep.
    int num_keep?;
    # Seed for reproducible outputs.
    int seed?;
    # Maximum number of tokens to predict.
    int num_predict?;
    # Top-k sampling parameter.
    int top_k?;
    # Top-p (nucleus) sampling parameter.
    decimal top_p?;
    # Minimum probability threshold.
    decimal min_p?;
    # Typical probability parameter.
    decimal typical_p?;
    # Number of last tokens to consider for repetition penalty.
    int repeat_last_n?;
    # Sampling temperature.
    decimal temperature?;
    # Penalty for repeated tokens.
    decimal repeat_penalty?;
    # Penalty for presence of certain tokens.
    decimal presence_penalty?;
    # Penalty based on token frequency.
    decimal frequency_penalty?;
    # Mirostat sampling mode.
    int mirostat?;
    # Mirostat tau parameter.
    decimal mirostat_tau?;
    # Mirostat eta parameter.
    decimal mirostat_eta?;
    # Whether to penalize newlines.
    boolean penalize_newline?;
    # List of stop sequences.
    string[] stop?;
    # Enable NUMA optimizations.
    boolean numa?;
    # Context window size.
    int num_ctx?;
    # Batch size for processing.
    int num_batch?;
    # Number of GPUs to use.
    int num_gpu?;
    # Main GPU index.
    int main_gpu?;
    # Optimize for low VRAM usage.
    boolean low_vram?;
    # Load only the vocabulary.
    boolean vocab_only?;
    # Use memory-mapped files.
    boolean use_mmap?;
    # Lock memory to prevent swapping.
    boolean use_mlock?;
    # Number of threads to use.
    int num_thread?;
};

public type Tool_function record {
    # The name of the function.
    string name;
    # A description of what the function does.
    string description?;
    # The JSON schema defining the parameters the function accepts.
    record {} parameters;
};

public type ToolCall record {
    ToolCall_function 'function?;
};

public type Message record {
    # The role of the message sender.
    "system"|"user"|"assistant"|"tool" role;
    # The text content of the message.
    string content;
    # List of base64-encoded images (for multimodal models like `llava`).
    string[] images?;
    # List of tool calls requested by the assistant (present when the model invokes tools).
    ToolCall[] tool_calls?;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

public type ToolCall_function record {
    # The name of the function to call.
    string name;
    # The arguments to pass to the function.
    record {} arguments;
};

public type ChatRequest record {
    # The model name in `model:tag` format (e.g., `llama3:70b`). Tag defaults to `latest` if omitted.
    string model;
    # List of messages in the chat history, including roles and content.
    Message[] messages;
    # List of tools (e.g., functions) available for the model to use, if supported.
    Tool[] tools?;
    # If set to `"json"`, the response content will be formatted as a JSON string.
    "json" format?;
    ChatOptions options?;
    # If `false`, returns a single response object instead of a stream. Defaults to `true`.
    boolean 'stream = true;
    # Duration the model stays loaded in memory after the request (e.g., `5m`). In nanoseconds if numeric.
    string|int keep_alive = "5m";
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

# Response when `stream` is `false`.
public type ChatSingleResponse record {
    # The model name used for generation.
    string model;
    # Timestamp of response creation.
    string created_at;
    # The assistant's complete response message.
    Message message;
    # Always `true` for a single response.
    boolean done;
    # Reason for completion (e.g., "stop").
    string done_reason?;
    # Total time spent generating the response in nanoseconds.
    int total_duration?;
    # Time spent loading the model in nanoseconds.
    int load_duration?;
    # Number of tokens in the prompt.
    int prompt_eval_count?;
    # Time spent evaluating the prompt in nanoseconds.
    int prompt_eval_duration?;
    # Number of tokens in the response.
    int eval_count?;
    # Time spent generating the response in nanoseconds.
    int eval_duration?;
};

# A single object in the stream of responses when `stream` is `true`.
public type ChatStreamResponse record {
    # The model name used for generation.
    string model;
    # Timestamp of response creation.
    string created_at;
    # The assistant's response message (content may be empty in the final response).
    Message message;
    # Indicates if this is the final response in the stream.
    boolean done;
    # Reason for completion (e.g., "stop"), present only in the final response.
    string done_reason?;
    # Total time spent generating the response in nanoseconds (final response only).
    int total_duration?;
    # Time spent loading the model in nanoseconds (final response only).
    int load_duration?;
    # Number of tokens in the prompt (final response only).
    int prompt_eval_count?;
    # Time spent evaluating the prompt in nanoseconds (final response only).
    int prompt_eval_duration?;
    # Number of tokens in the response (final response only).
    int eval_count?;
    # Time spent generating the response in nanoseconds (final response only).
    int eval_duration?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type Tool record {
    # The type of tool (currently only 'function' is supported).
    "function" 'type;
    Tool_function 'function?;
};
